name: "Ruby Upgrade Action"
description: "Automatically upgrade Ruby version in .ruby-version, Gemfile, Dockerfile, and GitHub Actions workflows."
author: "Andrew Nesbitt"
branding:
  icon: "refresh-ccw"
  color: "red"

inputs:
  repo-token:
    description: "GitHub token for creating pull requests."
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3.5'
        bundler-cache: true

    - name: Fetch latest Ruby version
      run: ./scripts/fetch_latest_ruby.sh
      shell: bash

    - name: Update Ruby version in files
      run: ./scripts/update_files.sh
      shell: bash

    - name: Install dependencies
      run: |
        if [ -f "Gemfile" ]; then
          bundle install
        else
          echo "Gemfile not found. Skipping bundle install."
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ inputs.repo-token }}
        title: "Upgrade Ruby to ${LATEST_VERSION}"
        body: |
          This pull request updates the Ruby version to the latest stable release: **${LATEST_VERSION}**.
        branch: "ruby-upgrade/${LATEST_VERSION}"
        commit-message: "Upgrade Ruby to ${LATEST_VERSION}"
        delete-branch: true